### PR TITLE
Create MANIFEST.in

### PR DESCRIPTION
**Pull request by jan-janssen**
Now when you run `python setup.py sdist`: 
```
running sdist
running egg_info
writing src/pyscal.egg-info/PKG-INFO
writing dependency_links to src/pyscal.egg-info/dependency_links.txt
writing requirements to src/pyscal.egg-info/requires.txt
writing top-level names to src/pyscal.egg-info/top_level.txt
reading manifest file 'src/pyscal.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'src/pyscal.egg-info/SOURCES.txt'
running check
creating pyscal-2.10.18
creating pyscal-2.10.18/lib
creating pyscal-2.10.18/lib/voro++
creating pyscal-2.10.18/src
creating pyscal-2.10.18/src/pyscal
creating pyscal-2.10.18/src/pyscal.egg-info
creating pyscal-2.10.18/src/pyscal/formats
creating pyscal-2.10.18/tests
copying files to pyscal-2.10.18...
copying LICENSE -> pyscal-2.10.18
copying MANIFEST.in -> pyscal-2.10.18
copying README.rst -> pyscal-2.10.18
copying setup.py -> pyscal-2.10.18
copying lib/voro++/voro++.cc -> pyscal-2.10.18/lib/voro++
copying src/pyscal/__init__.py -> pyscal-2.10.18/src/pyscal
copying src/pyscal/atom.cpp -> pyscal-2.10.18/src/pyscal
copying src/pyscal/atom.h -> pyscal-2.10.18/src/pyscal
copying src/pyscal/atom_binding.cpp -> pyscal-2.10.18/src/pyscal
copying src/pyscal/core.py -> pyscal-2.10.18/src/pyscal
copying src/pyscal/crystal_structures.py -> pyscal-2.10.18/src/pyscal
copying src/pyscal/misc.py -> pyscal-2.10.18/src/pyscal
copying src/pyscal/routines.py -> pyscal-2.10.18/src/pyscal
copying src/pyscal/system.cpp -> pyscal-2.10.18/src/pyscal
copying src/pyscal/system.h -> pyscal-2.10.18/src/pyscal
copying src/pyscal/system_binding.cpp -> pyscal-2.10.18/src/pyscal
copying src/pyscal/traj_process.py -> pyscal-2.10.18/src/pyscal
copying src/pyscal/trajectory.py -> pyscal-2.10.18/src/pyscal
copying src/pyscal/visualization.py -> pyscal-2.10.18/src/pyscal
copying src/pyscal.egg-info/PKG-INFO -> pyscal-2.10.18/src/pyscal.egg-info
copying src/pyscal.egg-info/SOURCES.txt -> pyscal-2.10.18/src/pyscal.egg-info
copying src/pyscal.egg-info/dependency_links.txt -> pyscal-2.10.18/src/pyscal.egg-info
copying src/pyscal.egg-info/not-zip-safe -> pyscal-2.10.18/src/pyscal.egg-info
copying src/pyscal.egg-info/requires.txt -> pyscal-2.10.18/src/pyscal.egg-info
copying src/pyscal.egg-info/top_level.txt -> pyscal-2.10.18/src/pyscal.egg-info
copying src/pyscal/formats/__init__.py -> pyscal-2.10.18/src/pyscal/formats
copying src/pyscal/formats/ase.py -> pyscal-2.10.18/src/pyscal/formats
copying src/pyscal/formats/lammps.py -> pyscal-2.10.18/src/pyscal/formats
copying src/pyscal/formats/mdtraj.py -> pyscal-2.10.18/src/pyscal/formats
copying src/pyscal/formats/vasp.py -> pyscal-2.10.18/src/pyscal/formats
copying tests/test_adaptive.py -> pyscal-2.10.18/tests
copying tests/test_angular.py -> pyscal-2.10.18/tests
copying tests/test_basic_atom.py -> pyscal-2.10.18/tests
copying tests/test_basic_system.py -> pyscal-2.10.18/tests
copying tests/test_basic_triclinic.py -> pyscal-2.10.18/tests
copying tests/test_centrosymmetry.py -> pyscal-2.10.18/tests
copying tests/test_chiparams.py -> pyscal-2.10.18/tests
copying tests/test_cna.py -> pyscal-2.10.18/tests
copying tests/test_crystal_structures.py -> pyscal-2.10.18/tests
copying tests/test_cubic_cell.py -> pyscal-2.10.18/tests
copying tests/test_cutoff.py -> pyscal-2.10.18/tests
copying tests/test_disorder.py -> pyscal-2.10.18/tests
copying tests/test_entropy.py -> pyscal-2.10.18/tests
copying tests/test_file.py -> pyscal-2.10.18/tests
copying tests/test_formats_system.py -> pyscal-2.10.18/tests
copying tests/test_neighbors.py -> pyscal-2.10.18/tests
copying tests/test_nucsize.py -> pyscal-2.10.18/tests
copying tests/test_q10.py -> pyscal-2.10.18/tests
copying tests/test_q11.py -> pyscal-2.10.18/tests
copying tests/test_q12.py -> pyscal-2.10.18/tests
copying tests/test_q2.py -> pyscal-2.10.18/tests
copying tests/test_q3.py -> pyscal-2.10.18/tests
copying tests/test_q4.py -> pyscal-2.10.18/tests
copying tests/test_q5.py -> pyscal-2.10.18/tests
copying tests/test_q6.py -> pyscal-2.10.18/tests
copying tests/test_q7.py -> pyscal-2.10.18/tests
copying tests/test_q8.py -> pyscal-2.10.18/tests
copying tests/test_q9.py -> pyscal-2.10.18/tests
copying tests/test_q_atom.py -> pyscal-2.10.18/tests
copying tests/test_q_system.py -> pyscal-2.10.18/tests
copying tests/test_qlist.py -> pyscal-2.10.18/tests
copying tests/test_rdf.py -> pyscal-2.10.18/tests
copying tests/test_sro.py -> pyscal-2.10.18/tests
copying tests/test_traj_process.py -> pyscal-2.10.18/tests
copying tests/test_trajectory.py -> pyscal-2.10.18/tests
copying tests/test_volume.py -> pyscal-2.10.18/tests
copying tests/test_voronoi.py -> pyscal-2.10.18/tests
Writing pyscal-2.10.18/setup.cfg
Creating tar archive
removing 'pyscal-2.10.18' (and everything under it)
```
previously the following files were not included:
```
copying src/pyscal/atom.h -> pyscal-2.10.18/src/pyscal
copying src/pyscal/system.h -> pyscal-2.10.18/src/pyscal
```

### CODE REVIEW

**Comment by srmnitc** [comment]
@jan-janssen I am actually also building all wheels in CI and adding them to them pypi release. This was on a branch and was not yet merged into master. Now it is done. Therefore I am gonna go ahead and close this pull request. I apologize for my slow reply since I am on vacation.

**Comment by srmnitc** [comment]
Oh, maybe this is still needed for the conda forge pull request? I am not sure if we need another package called pyscal2 on conda-forge though. @jan-janssen do you think it would bring any significant benefits?

**Comment by srmnitc** [comment]
I am not sure why the windows build fails either..

**Comment by jan-janssen** [comment]
> Oh, maybe this is still needed for the conda forge pull request? I am not sure if we need another package called pyscal2 on conda-forge though. @jan-janssen do you think it would bring any significant benefits?

I guess the consistent naming would make it easier for people.

**Pull request closed without merging**
